import React, { useState, useEffect } from 'react';
import { MainLayout } from '../components/MainLayout';
import { apiClient } from '../utils/api';
import { PageHeader, StatCard, EmptyState, Modal, Input, Select, Button, Badge } from '../components/ui-kit';
import { useAuth } from '../context/AuthContext';
import { Users, Shield, Building2, Database, UserCog, UserX, RefreshCw, Key, LogOut, Clock, Copy, CheckCircle } from 'lucide-react';

const ROLES = [
  { value: 'user', label: 'User' },
  { value: 'employee', label: 'Employee' },
  { value: 'team_lead', label: 'Team Lead' },
  { value: 'manager', label: 'Manager' },
  { value: 'admin', label: 'Admin' },
  { value: 'owner', label: 'Owner' },
];

const STATUSES = [
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' },
  { value: 'suspended', label: 'Suspended' },
];

export const Admin = () => {
  const { user } = useAuth();
  const [tab, setTab] = useState('users');
  const [users, setUsers] = useState([]);
  const [sessions, setSessions] = useState([]);
  const [stats, setStats] = useState({});
  const [loading, setLoading] = useState(true);
  const [editingUser, setEditingUser] = useState(null);
  const [resetUser, setResetUser] = useState(null);
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [resetPasswordInput, setResetPasswordInput] = useState('');
  const [autoGeneratedPassword, setAutoGeneratedPassword] = useState('');
  const [copySuccess, setCopySuccess] = useState(false);
  const [toast, setToast] = useState(null);

  useEffect(() => { fetchData(); }, []);
  useEffect(() => { if (tab === 'sessions') fetchSessions(); }, [tab]);

  const showToast = (message, type = 'success') => {
    setToast({ message, type });
    setTimeout(() => setToast(null), 3500);
  };

  const fetchData = async () => {
    setLoading(true);
    try {
      const [u, s] = await Promise.all([
        apiClient.get('/users'),
        apiClient.get('/admin/stats'),
      ]);
      setUsers(u.data.users || []);
      setStats(s.data || {});
    } catch (e) { console.error(e); }
    finally { setLoading(false); }
  };

  const fetchSessions = async () => {
    try {
      const res = await apiClient.get('/admin/sessions');
      setSessions(res.data.sessions || []);
    } catch (e) { console.error(e); }
  };

  const handleUpdateUser = async (e) => {
    e.preventDefault();
    setError(''); setSubmitting(true);
    try {
      const payload = {
        username: editingUser.username,
        name: editingUser.name,
        email: editingUser.email,
        role: editingUser.role,
        status: editingUser.status,
        job_title: editingUser.job_title,
        department: editingUser.department,
      };
      await apiClient.put(`/admin/users/${editingUser.user_id}`, payload);
      setEditingUser(null);
      fetchData();
      showToast('User updated successfully');
    } catch (err) {
      const d = err.response?.data?.detail;
      setError(typeof d === 'string' ? d : 'Failed to update user');
    } finally { setSubmitting(false); }
  };

  const handleResetPassword = async (autoGenerate) => {
    if (!resetUser) return;
    setError(''); setSubmitting(true);
    try {
      const body = autoGenerate ? {} : { new_password: resetPasswordInput };
      const res = await apiClient.post(`/admin/users/${resetUser.user_id}/reset-password`, body);
      if (autoGenerate) {
        setAutoGeneratedPassword(res.data.new_password);
      } else {
        showToast('Password reset. User has been logged out from all devices.');
        setResetUser(null);
        setResetPasswordInput('');
      }
    } catch (err) {
      const d = err.response?.data?.detail;
      setError(typeof d === 'string' ? d : 'Failed to reset password');
    } finally { setSubmitting(false); }
  };

  const handleToggleStatus = async (u, newStatus) => {
    try {
      await apiClient.put(`/admin/users/${u.user_id}/toggle-status`, { status: newStatus });
      fetchData();
      showToast(`User ${newStatus === 'active' ? 'enabled' : 'disabled'}`);
    } catch (err) {
      showToast('Failed to change status', 'error');
    }
  };

  const handleForceLogout = async (u) => {
    if (!window.confirm(`Force logout ${u.name}? All their active sessions will end.`)) return;
    try {
      const res = await apiClient.post(`/admin/users/${u.user_id}/force-logout`);
      showToast(`${res.data.sessions_revoked} session(s) revoked`);
      if (tab === 'sessions') fetchSessions();
    } catch (err) {
      showToast('Failed to force logout', 'error');
    }
  };

  const handleRevokeSession = async (token) => {
    try {
      await apiClient.delete(`/admin/sessions/${token.replace('...', '')}`);
      showToast('Session revoked');
      fetchSessions();
    } catch (err) { showToast('Failed to revoke session', 'error'); }
  };

  const copyToClipboard = (text) => {
    navigator.clipboard?.writeText(text).then(() => {
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    });
  };

  const isAdmin = user?.role === 'owner' || user?.role === 'admin';

  if (!isAdmin) {
    return (
      <MainLayout>
        <EmptyState icon={Shield} title="Access Denied" description="You need admin privileges to access this page." />
      </MainLayout>
    );
  }

  return (
    <MainLayout>
      <div className="space-y-6" data-testid="admin-panel">
        <PageHeader title="Super Admin Portal" description="Full account management — users, sessions, roles, and system settings" />

        {toast && (
          <div
            className={`fixed top-20 right-6 z-50 rounded-lg border px-4 py-3 shadow-lg animate-fade-in ${
              toast.type === 'error'
                ? 'border-destructive/20 bg-destructive/10 text-destructive'
                : 'border-success/20 bg-success/10 text-success'
            }`}
            data-testid="admin-toast"
          >
            {toast.message}
          </div>
        )}

        <div className="bento-grid">
          <StatCard title="Total Users" value={stats.total_users || 0} icon={Users} testId="stat-total-users" />
          <StatCard title="Active Users" value={stats.active_users || 0} icon={UserCog} testId="stat-active-users" />
          <StatCard title="Organizations" value={stats.total_organizations || 0} icon={Building2} />
          <StatCard title="Files Stored" value={stats.total_files || 0} icon={Database} />
        </div>

        <div className="border-b border-border">
          <div className="flex gap-8">
            {['users', 'sessions', 'roles', 'settings'].map((t) => (
              <button
                key={t}
                onClick={() => setTab(t)}
                className={`border-b-2 pb-3 text-sm font-medium capitalize transition-colors ${
                  tab === t ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'
                }`}
                data-testid={`admin-tab-${t}`}
              >
                {t}
              </button>
            ))}
          </div>
        </div>

        {tab === 'users' && (
          <div className="rounded-xl border border-border bg-surface overflow-hidden" data-testid="admin-users-table">
            {loading ? (
              <div className="flex justify-center py-12"><div className="animate-spin h-8 w-8 border-4 border-primary border-t-transparent rounded-full"></div></div>
            ) : users.length === 0 ? (
              <EmptyState icon={Users} title="No users yet" />
            ) : (
              <table className="w-full data-table">
                <thead className="bg-surface-elevated border-b border-border">
                  <tr>
                    <th className="px-6 py-3 text-left">User</th>
                    <th className="px-6 py-3 text-left">Username</th>
                    <th className="px-6 py-3 text-left">Role</th>
                    <th className="px-6 py-3 text-left">Status</th>
                    <th className="px-6 py-3 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {users.map((u) => (
                    <tr key={u.user_id} className="border-b border-border hover:bg-surface-elevated transition-colors" data-testid="admin-user-row">
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-3">
                          <div className="flex h-9 w-9 items-center justify-center rounded-full bg-primary text-xs font-medium text-white">
                            {u.name?.charAt(0)?.toUpperCase() || 'U'}
                          </div>
                          <div>
                            <p className="font-medium text-foreground">{u.name}</p>
                            <p className="text-xs text-muted-foreground">{u.email}</p>
                          </div>
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <code className="rounded bg-surface-elevated px-2 py-1 text-xs text-foreground font-mono">{u.username || '—'}</code>
                      </td>
                      <td className="px-6 py-4">
                        <Badge variant={u.role === 'owner' ? 'info' : u.role === 'admin' ? 'warning' : 'default'}>{u.role}</Badge>
                      </td>
                      <td className="px-6 py-4">
                        <Badge variant={u.status === 'active' ? 'success' : u.status === 'suspended' ? 'error' : 'warning'}>
                          {u.status}
                        </Badge>
                      </td>
                      <td className="px-6 py-4 text-right">
                        <div className="flex justify-end gap-1">
                          <button
                            onClick={() => setEditingUser({ ...u })}
                            className="rounded p-2 text-muted-foreground hover:text-primary hover:bg-primary/10 transition-colors"
                            data-testid={`edit-user-${u.user_id}`}
                            title="Edit user"
                          >
                            <UserCog className="h-4 w-4" />
                          </button>
                          <button
                            onClick={() => { setResetUser(u); setResetPasswordInput(''); setAutoGeneratedPassword(''); }}
                            className="rounded p-2 text-muted-foreground hover:text-warning hover:bg-warning/10 transition-colors"
                            data-testid={`reset-password-${u.user_id}`}
                            title="Reset password"
                          >
                            <Key className="h-4 w-4" />
                          </button>
                          {u.user_id !== user?.user_id && (
                            <>
                              <button
                                onClick={() => handleForceLogout(u)}
                                className="rounded p-2 text-muted-foreground hover:text-warning hover:bg-warning/10 transition-colors"
                                data-testid={`force-logout-${u.user_id}`}
                                title="Force logout"
                              >
                                <LogOut className="h-4 w-4" />
                              </button>
                              <button
                                onClick={() => handleToggleStatus(u, u.status === 'active' ? 'suspended' : 'active')}
                                className={`rounded p-2 transition-colors ${
                                  u.status === 'active'
                                    ? 'text-muted-foreground hover:text-destructive hover:bg-destructive/10'
                                    : 'text-muted-foreground hover:text-success hover:bg-success/10'
                                }`}
                                data-testid={`toggle-status-${u.user_id}`}
                                title={u.status === 'active' ? 'Disable account' : 'Enable account'}
                              >
                                <UserX className="h-4 w-4" />
                              </button>
                            </>
                          )}
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        )}

        {tab === 'sessions' && (
          <div className="rounded-xl border border-border bg-surface overflow-hidden" data-testid="admin-sessions-table">
            <div className="flex items-center justify-between border-b border-border p-4">
              <div>
                <h3 className="font-semibold text-foreground">Active Sessions</h3>
                <p className="text-xs text-muted-foreground">{sessions.length} active sessions</p>
              </div>
              <Button variant="secondary" size="sm" onClick={fetchSessions} data-testid="refresh-sessions-button">
                <RefreshCw className="mr-2 inline h-4 w-4" /> Refresh
              </Button>
            </div>
            {sessions.length === 0 ? (
              <EmptyState icon={Clock} title="No active sessions" />
            ) : (
              <table className="w-full data-table">
                <thead className="bg-surface-elevated border-b border-border">
                  <tr>
                    <th className="px-6 py-3 text-left">User</th>
                    <th className="px-6 py-3 text-left">Role</th>
                    <th className="px-6 py-3 text-left">Session Token</th>
                    <th className="px-6 py-3 text-left">Created</th>
                    <th className="px-6 py-3 text-left">Expires</th>
                    <th className="px-6 py-3 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {sessions.map((s, idx) => (
                    <tr key={idx} className="border-b border-border hover:bg-surface-elevated transition-colors" data-testid="session-row">
                      <td className="px-6 py-4">
                        <p className="font-medium text-foreground">{s.user?.name || 'Unknown'}</p>
                        <p className="text-xs text-muted-foreground">{s.user?.username || s.user?.email || '—'}</p>
                      </td>
                      <td className="px-6 py-4"><Badge variant={s.user?.role === 'owner' ? 'info' : s.user?.role === 'admin' ? 'warning' : 'default'}>{s.user?.role || '—'}</Badge></td>
                      <td className="px-6 py-4"><code className="text-xs text-muted-foreground font-mono">{s.session_token}</code></td>
                      <td className="px-6 py-4 text-xs text-muted-foreground">{s.created_at ? new Date(s.created_at).toLocaleString() : '—'}</td>
                      <td className="px-6 py-4 text-xs text-muted-foreground">{s.expires_at ? new Date(s.expires_at).toLocaleDateString() : '—'}</td>
                      <td className="px-6 py-4 text-right">
                        <button
                          onClick={() => handleRevokeSession(s.session_token)}
                          className="rounded px-3 py-1 text-xs text-destructive hover:bg-destructive/10 transition-colors"
                          data-testid={`revoke-session-${idx}`}
                        >
                          Revoke
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        )}

        {tab === 'roles' && (
          <div className="rounded-xl border border-border bg-surface p-6">
            <h3 className="mb-4 text-lg font-semibold text-foreground">System Roles</h3>
            <div className="space-y-3">
              {ROLES.map((role) => (
                <div key={role.value} className="flex items-center justify-between rounded-lg border border-border p-4">
                  <div className="flex items-center gap-3">
                    <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10"><Shield className="h-5 w-5 text-primary" /></div>
                    <div>
                      <p className="font-medium text-foreground">{role.label}</p>
                      <p className="text-sm text-muted-foreground">{users.filter(u => u.role === role.value).length} users</p>
                    </div>
                  </div>
                  <Badge variant="info">{role.value}</Badge>
                </div>
              ))}
            </div>
          </div>
        )}

        {tab === 'settings' && (
          <div className="rounded-xl border border-border bg-surface p-6">
            <h3 className="mb-4 text-lg font-semibold text-foreground">System Settings</h3>
            <div className="space-y-4">
              <div className="flex items-center justify-between rounded-lg border border-border p-4">
                <div><p className="font-medium text-foreground">Organization Name</p><p className="text-sm text-muted-foreground">WebBuilder</p></div>
                <Button variant="secondary" size="sm">Edit</Button>
              </div>
              <div className="flex items-center justify-between rounded-lg border border-border p-4">
                <div><p className="font-medium text-foreground">Founder</p><p className="text-sm text-muted-foreground">Ark Dwivedi</p></div>
                <Badge variant="info">Owner</Badge>
              </div>
              <div className="flex items-center justify-between rounded-lg border border-border p-4">
                <div><p className="font-medium text-foreground">Co-Founder</p><p className="text-sm text-muted-foreground">Utkarsh Mishra</p></div>
                <Badge variant="info">Owner</Badge>
              </div>
              <div className="flex items-center justify-between rounded-lg border border-border p-4">
                <div><p className="font-medium text-foreground">Refresh Data</p><p className="text-sm text-muted-foreground">Reload latest statistics</p></div>
                <Button variant="secondary" size="sm" onClick={fetchData}><RefreshCw className="mr-2 inline h-4 w-4" />Refresh</Button>
              </div>
            </div>
          </div>
        )}

        {editingUser && (
          <Modal open={!!editingUser} onClose={() => setEditingUser(null)} title="Edit User" size="lg">
            {error && <div className="mt-4 rounded-lg border border-destructive/20 bg-destructive/10 p-3 text-sm text-destructive" data-testid="edit-user-error">{error}</div>}
            <form onSubmit={handleUpdateUser} className="mt-6 space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <Input label="Username" value={editingUser.username || ''} onChange={(e) => setEditingUser({ ...editingUser, username: e.target.value })} data-testid="edit-user-username" />
                <Input label="Full Name" value={editingUser.name || ''} onChange={(e) => setEditingUser({ ...editingUser, name: e.target.value })} data-testid="edit-user-name" />
              </div>
              <Input label="Email" type="email" value={editingUser.email || ''} onChange={(e) => setEditingUser({ ...editingUser, email: e.target.value })} data-testid="edit-user-email" />
              <div className="grid grid-cols-2 gap-4">
                <Select label="Role" value={editingUser.role} onChange={(e) => setEditingUser({ ...editingUser, role: e.target.value })} options={ROLES} data-testid="edit-user-role" />
                <Select label="Status" value={editingUser.status || 'active'} onChange={(e) => setEditingUser({ ...editingUser, status: e.target.value })} options={STATUSES} data-testid="edit-user-status" />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <Input label="Job Title" value={editingUser.job_title || ''} onChange={(e) => setEditingUser({ ...editingUser, job_title: e.target.value })} />
                <Input label="Department" value={editingUser.department || ''} onChange={(e) => setEditingUser({ ...editingUser, department: e.target.value })} />
              </div>
              <div className="flex gap-3 pt-4">
                <Button type="button" variant="secondary" className="flex-1" onClick={() => setEditingUser(null)}>Cancel</Button>
                <Button type="submit" disabled={submitting} className="flex-1" data-testid="save-user-button">
                  {submitting ? 'Saving...' : 'Save Changes'}
                </Button>
              </div>
            </form>
          </Modal>
        )}

        {resetUser && (
          <Modal open={!!resetUser} onClose={() => { setResetUser(null); setResetPasswordInput(''); setAutoGeneratedPassword(''); }} title={`Reset password for ${resetUser.name}`}>
            {error && <div className="mt-4 rounded-lg border border-destructive/20 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}
            {autoGeneratedPassword ? (
              <div className="mt-6 space-y-4">
                <div className="rounded-lg border border-success/20 bg-success/10 p-4">
                  <p className="text-sm text-success font-medium mb-2">Password reset successfully</p>
                  <p className="text-xs text-muted-foreground mb-3">Share this password securely with the user. All their sessions have been logged out.</p>
                  <div className="flex items-center gap-2">
                    <code className="flex-1 rounded bg-surface-elevated px-3 py-2 text-sm font-mono text-foreground break-all" data-testid="generated-password-value">{autoGeneratedPassword}</code>
                    <button onClick={() => copyToClipboard(autoGeneratedPassword)} className="rounded p-2 text-muted-foreground hover:text-primary hover:bg-primary/10 transition-colors" data-testid="copy-password-button">
                      {copySuccess ? <CheckCircle className="h-5 w-5 text-success" /> : <Copy className="h-5 w-5" />}
                    </button>
                  </div>
                </div>
                <Button className="w-full" onClick={() => { setResetUser(null); setResetPasswordInput(''); setAutoGeneratedPassword(''); }}>Done</Button>
              </div>
            ) : (
              <div className="mt-6 space-y-4">
                <div>
                  <label className="mb-1.5 block text-sm font-medium text-foreground">New Password (leave blank to auto-generate)</label>
                  <input
                    type="text"
                    value={resetPasswordInput}
                    onChange={(e) => setResetPasswordInput(e.target.value)}
                    placeholder="Enter custom password or leave blank"
                    minLength={4}
                    className="w-full rounded-lg border border-input bg-background px-4 py-2.5 text-foreground focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20 font-mono"
                    data-testid="new-password-input"
                  />
                  <p className="mt-1 text-xs text-muted-foreground">Min 4 characters. All sessions for this user will be revoked.</p>
                </div>
                <div className="flex gap-3 pt-2">
                  <Button type="button" variant="secondary" className="flex-1" onClick={() => setResetUser(null)}>Cancel</Button>
                  <Button
                    onClick={() => handleResetPassword(true)}
                    disabled={submitting}
                    variant="secondary"
                    data-testid="auto-generate-button"
                  >
                    Auto-generate
                  </Button>
                  <Button
                    onClick={() => handleResetPassword(false)}
                    disabled={submitting || resetPasswordInput.length < 4}
                    data-testid="submit-reset-password-button"
                  >
                    {submitting ? 'Resetting...' : 'Reset Password'}
                  </Button>
                </div>
              </div>
            )}
          </Modal>
        )}
      </div>
    </MainLayout>
  );
};
